### ISSUE TITLE
Creating a body map using named locations

### ISSUE THREAD

**Issue by jgburg** [emcramer/CHOIRBM#3]
Dear Eric,

Is it possible to create a body map in CHOIRBM using named locations for pain distributions instead of the numeric system?

I would like to plot each individual and create a heatmap of the pain distribution by group on a pain mannequin.

If you have have ideas/suggestions please let me know.

BW

Jamie

**Comment by emcramer** [comment]
Hi Jamie, is there a standard nomenclature for named distributions? Otherwise it would be necessary to provide a mapping from the numeric system to named distributions each time you generate a graphic.

**Comment by jgburg** [comment]
Hi Eric,

Thanks for your message. Would it be possible to clarify whether there is a list of regions/body parts which are associated with each number? This would be good to add to our prospective data collection from pain questionnaires with a mannequin.




Sent from Outlook for Android<https://aka.ms/AAb9ysg>

Kind regards,


Jamie Burgess

PhD Candidate

Diabetes & Endocrinology Research

Institute of Cardiovascular & Metabolic Medicine

University of Liverpool

Aintree University Hospital &

The Walton Centre

0151 529 5171



Twitter: @jgburgess2



My NCBI Bibliography: https://www.ncbi.nlm.nih.gov/myncbi/1jC4tygAi6ssiW/bibliography/public/
________________________________

**Comment by emcramer** [comment]
In my experience, researchers have chosen to group different numbered sections of the map into larger regions that suit their specific needs. For example, these authors (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8577690/) grouped it like this:
![nihms-1705118-f0001](https://github.com/emcramer/CHOIRBM/assets/13970720/21b87655-412c-4f71-b259-66bec002fa9b)

I have seen it done a few other ways too, where different numbers are associated with a particular body part (or vice versa). Is there a particular type of graphical output that you are looking for?

**Comment by emcramer** [comment]
@jgburg have you figured out your body-part grouping scheme? If so, then I will close this issue.

**Comment by jgburg** [comment]
Hi Eric,

Thanks for your message. Yes, I believe those approaches will work.

If I get stuck with the coding could I contact you again?

Best Wishes,
Jamie

**Comment by emcramer** [comment]
Yes, you may reopen this issue here if you have trouble.
